### ISSUE TITLE
configure: "invalid jira location" trying to access hosted JIRA

### ISSUE THREAD

**Issue by msabramo** [alisaifee/jira-cli#22]
```
$ jira-cli --version
2.0.12

$ jira-cli configure
Base url for the jira instance: https://monkeys.jira.com
username: marca
password:
invalid jira location

Base url for the jira instance: http://monkeys.jira.com
username: marca
password:
invalid jira location

Base url for the jira instance: https://monkeys.jira.com
username: marca
password:
invalid jira location
```

**Comment by alisaifee** [comment]
Hi @msabramo. Any possibility you could hook me up with a test account on your jira instance to try and debug this issue?

**Comment by alisaifee** [comment]
@msabramo : I'm hoping version `2.0.13` fixes your issue. I think the reason is that that old soap rpc method (which was hardcoded for the configuration step) is not being supported in the newer versions of jira and therefore when you tried to configure it failed.

If you try with 
```
jira-cli --v2 --protocol=rest configure
```
you should be able to go through with the setup.

**Comment by swamisun** [comment]
@alisaifee That still didn't solve the issue

`
47 bash>> jira-cli --version
2.0.17
48 bash>> sudo jira-cli --v2 --protocol=rest configure
Password:
Base url for the jira instance: https://jira.#####.com/
username: swami
would you like to persist the credentials to the local keyring? [y/n]:y
swami@swami-MBP15-QR1QX:~/github/go-jira 2016-05-17 11:22:55 [master]
49 bash>> jira-cli view XXX-726
swami@swami-MBP15-QR1QX:~/github/go-jira 2016-05-17 11:22:59 [master]`

Thoughts?
