### ISSUE TITLE
update ticket comment in v2 from cmdline

### ISSUE THREAD

**Issue by mthauth** [alisaifee/jira-cli#8]
In v1 its possible to write a command w/o popup editor:
jira-cli -j BE-193 -c "lorem ipsum"

In v2 that feature is missing - an editor pops up and interrupts
jira-cli --v2 update BE-193 --comment
lorem ipsum

Is there a way to get an equal feature in v2 like in v1?
Piped-in doesn't work, maybe an easteregg-parameter, etc?
Feature is worthful for scripting, f.e.

Thanks for your reply!

**Comment by jpage4500** [comment]
Hi - I found this project when looking to create a git 'post-commit' script that would look for JIRA issues in a git check-in comments field and add the comment to the JIRA issue.

Everything was looking great until I realized I can't pass in the comment via command-line because of the editor. Is there any other work-around you can think of to prevent this?

I could fork and modify the source but not sure how to build & install it (much less getting it installed for other developers here)..

--------
echo "this is my check-in comment" | jira-cli update $JIRA --comment

Vim: Warning: Input is not from a terminal
Vim: Error reading input, exiting...
Vim: preserving files...
Vim: Finished.

**Comment by jpage4500** [comment]
quick update - I took a stab at implementing this feature in a fork. My first python code so I just tried to get it to work. Ideally, though, it would be able to use a passed-in parameter but would still fall-back on opening the vim editor if nothing was passed.

Anyway, it suits my purposes for now and can be found here if anyone wants to take it further and get it merged back here (or make update suggestions and I'll make them and open a pull request)

usage:
 jira-cli update JIRA-129 --comment="this is a comment"

fork:
https://github.com/jpage4500/jira-cli

**Comment by alisaifee** [comment]
This should be fixed in 7c04f5627034f8becb9e6a596a6a014fcc978d9c. Both passing the comment as a command line parameter and the editor should be supported.

I haven't made a release on pypi yet, because I no longer have access to a working jira instance. If one of you could test it I'll make the release.

**Comment by alisaifee** [comment]
Closing this as it's been addressed.
